---
format: live-html
engine: knitr
lightbox: true
webr:
  resources:
    - https://raw.githubusercontent.com/LizzieWadsworth/Level-4-R-course-book/refs/heads/main/Datasets/LocustSerotonin.csv
  packages:
    - ggplot2
    - dplyr
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

# Discrete verses continuous scale

Here we have three distinct treatment groups. This is a discrete scale - no locusts were crowded for 1.5 hours for instance.

As this is numerical, it's automatically taken as a continuous scale. We can see this when we use `fill =` to colour the boxplots by treatmentTime.

```{webr}
# Import the CSV file into an R Dataframe
locust_df <- read.csv("LocustSerotonin.csv") 
head(locust_df)

# Plot the data using ggplot package
ggplot(locust_df, aes(x = treatmentTime, 
                      y = serotoninLevel, 
                      group = treatmentTime, 
                      fill = treatmentTime)) +
  geom_boxplot() 
```

To make the same dataset use a discrete scale for this value, we can use the `as.factor()` function.

We can use `locust_df$treatmentTime` to select the whole column. We can then use this as an argument by putting it inside the function: `as.factor(locust_df$treatmentTime)`

Finally, if we just did the above it would convert our values to a factor **but not save this**. We can use `<-` to **overwrite** our original column which had the numerical values.

Putting that together we get:

`locust_df$treatmentTime <- as.factor(locust_df$treatmentTime)`

```{webr}
# Import the CSV file into an R Dataframe
locust_df <- read.csv("LocustSerotonin.csv") 
head(locust_df)

# Convert treatment time column to discrete values
locust_df$treatmentTime <- as.factor(locust_df$treatmentTime)

# Plot the data using ggplot package
ggplot(locust_df, aes(x = treatmentTime, 
                      y = serotoninLevel, 
                      group = treatmentTime, 
                      fill = treatmentTime)) +
  geom_boxplot() 
```
