---
format: live-html
engine: knitr
lightbox: true
webr:
  resources:
    - https://raw.githubusercontent.com/LizzieWadsworth/Level-4-R-course-book/refs/heads/main/Datasets/LocustSerotonin.csv
  packages:
    - ggplot2
    - dplyr
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

# Separate by categorical group (sex)

If we add a color based on a categorical variable, this will then calculate the regression separately for each group.

See below, where we have assigned each point a colour based on sex:

```{r}
#| eval: false
# Load ggplot2 AND ggpubr packages
library(ggplot2)
library(ggpubr)

# Open heart.csv and save as a dataframe
heart_df <- read.csv("heart.csv") 

# Plot the heart data as before but setting color to the sex column
ggplot(heart_df, aes(x = age, y = restbp, color = sex)) +
  geom_point() +
  # add a pearson correlation from the stat_cor function
  stat_cor(method = 'pearson') +
  # add linear regression line using geom_smooth
  geom_smooth(method='lm', formula= y~x)
```
```{r}
#| echo: false
# Load ggplot2 AND ggpubr packages
library(ggplot2)
library(ggpubr)

# Open heart.csv and save as a dataframe
heart_df <- read.csv("../Datasets/heart.csv") 

# Plot the heart data as before but setting color to the sex column
ggplot(heart_df, aes(x = age, y = restbp, color = sex)) +
  geom_point() +
  # add a pearson correlation from the stat_cor function
  stat_cor(method = 'pearson') +
  # add linear regression line using geom_smooth
  geom_smooth(method='lm', formula= y~x)
```