---
format: live-html
engine: knitr
lightbox: true
webr:
  resources:
    - https://raw.githubusercontent.com/LizzieWadsworth/Level-4-R-course-book/refs/heads/main/Datasets/LocustSerotonin.csv
  packages:
    - ggplot2
    - dplyr
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

# T-test options 

This was our T-test from the previous page: 

```{r}
# Create a vector of values for each of our columns
NonDiabetic = c(82,87,79,79,86,70,98,92,75,90,73,70,87,88,96,93) # NonDiabetic glycemia values
Diabetic = c(112,110,94,121,85,125,80,122,117,116,99,90,99,95,84,84) # Diabetic glycemia values

# Run an unpaired t test using t.test()
unpaired_t_test_result <- t.test(NonDiabetic, Diabetic)
# Print the result to the console
unpaired_t_test_result
```

## T-test options

We didn't have to use any **options** here as the default test is two tailed, unpaired, and assuming the variance is not equal. If you want to change any of the options, you can try:

-   **alternative** for two tailed or one tailed
    -   "two.sided" for a two tailed test,
    -   "greater" for one tailed where the mean of the first variable is greater than the mean of the second variable
    -   "less" for one tailed where the mean of the first variable is greater than the mean of the second variable
    -   `unpaired_t_test_result <- t.test(NonDiabetic, Diabetic, alternative="greater")`
-   **paired** for paired or unpaired
    -   TRUE for paired
    -   FALSE for unpaired
    -   `unpaired_t_test_result <- t.test(NonDiabetic, Diabetic, paired = TRUE)`
-   **mu** mean, for comparison for a one-tailed test