---
format: live-html
engine: knitr
lightbox: true
webr:
  resources:
    - https://raw.githubusercontent.com/LizzieWadsworth/Level-4-R-course-book/refs/heads/main/Datasets/LocustSerotonin.csv
  packages:
    - ggplot2
    - dplyr
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

#  Violin plots

Violin plots are similar to box plots, but they show more information on what the *distribution* is. A violin plot can sometimes give more useful information than a box plot.

To change from a box plot to a violin plot, you only need to change from `geom_boxplot()` to `geom_violin()`.

```{r}
#| eval: false
library(ggplot2)
# Import the CSV file into an R Dataframe
locust_df <- read.csv("LocustSerotonin.csv") 

# Convert treatment time column to discrete values
locust_df$treatmentTime <- as.factor(locust_df$treatmentTime)

# Plot the data using ggplot package
ggplot(locust_df, aes(x = treatmentTime, 
                      y = serotoninLevel, 
                      group = treatmentTime, 
                      fill = treatmentTime)) +

  geom_violin() 
```
```{r}
#| echo: false
library(ggplot2)
# Import the CSV file into an R Dataframe
locust_df <- read.csv("../Datasets/LocustSerotonin.csv") 

# Convert treatment time column to discrete values
locust_df$treatmentTime <- as.factor(locust_df$treatmentTime)

# Plot the data using ggplot package
ggplot(locust_df, aes(x = treatmentTime, 
                      y = serotoninLevel, 
                      group = treatmentTime, 
                      fill = treatmentTime)) +

  geom_violin() 
```

*Question:* If you add the line `+ geom_point()`, what happens?